name: Auto approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - name: Auto approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Print github head_ref
      run: 'echo github.gead_ref is: ${{ github.head_ref }}'
