name: Auto approve
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - uses: actions/checkout@v2
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: |
        echo github.gead_ref is: $GITHUB_HEAD_REF
